version: "3.9"

services:
  api:
    container_name: api
    image: produtos_categorias
    build: .
    ports:
      - 3333:3333
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=defaultdb
    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql